### ISSUE TITLE
too much failed

### ISSUE THREAD

**Issue by LuisRain** [the-laziest-coder/galxe-aio#5]
Twitter is a new one, discord is a new one.
I can only log in to galxe, and almost nothing else can be done.

err:
1、 Failed to complete "subsquid - Twitter Followers": Get my username error: [WinEr
2、Failed to get fingerprint: TypeError: window.initGeetest4
3、Galxe error: GalxeIDExist request failed: Failed to perform, ErrCode: 56, Reason: 'Recv failure

I only saw one successful connection to twitter

**Comment by LuisRain** [comment]
twitter too easily controlled by risk.

**Comment by the-laziest-coder** [comment]
fixed in update
