### ISSUE TITLE
Failed to get fingerprint: TypeError: window.initGeetest4 is not a function

### ISSUE THREAD

**Issue by datafu** [the-laziest-coder/galxe-aio#8]
ERROR   | Failed to get fingerprint: TypeError: window.initGeetest4 is not a function
    at eval (eval at evaluate (:226:30), <anonymous>:1:8)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

**Comment by constZinovyev** [comment]
i have the same problem
it appeared yesterday

**Comment by reediklox** [comment]
Link in fingerprint.py is broken. 
It is need to be used "https://app.galxe.com/quest" instead of "https://galxe.com/protocol". 
I solved this issue by this change.

**Comment by timfame** [comment]
Thanks, will update it

**Comment by the-laziest-coder** [comment]
thanks to @reediklox , fixed in update
